import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { desc } from "drizzle-orm";
import { db,schema } from "@/lib/db";
import { requirePermission } from "@/lib/auth/authorization";
import { AuthorizationError } from "@/lib/auth/authorization-core";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import styles from "./Dashboard.module.css";
export const metadata:Metadata={title:"Dashboard"};
export default async function AdminDashboardPage(){await requirePermission("dashboard.view").catch(e=>{if(e instanceof AuthorizationError)notFound();throw e;});const[projects,messages,testimonials,services,experience,recent]=await Promise.all([db.select().from(schema.portfolioProjects),db.select().from(schema.contactMessages),db.select().from(schema.testimonials),db.select().from(schema.services),db.select().from(schema.experiences),db.select().from(schema.contactMessages).orderBy(desc(schema.contactMessages.createdAt)).limit(5)]);const cards=[{label:"Portfolio / Projects",href:"/admin/portfolio",published:projects.filter(x=>x.status==="published").length,pending:projects.filter(x=>x.status!=="published").length},{label:"Testimonials",href:"/admin/testimonials",published:testimonials.filter(x=>x.status==="published").length,pending:testimonials.filter(x=>x.status!=="published").length},{label:"Services",href:"/admin/services",published:services.filter(x=>x.isActive).length,pending:services.filter(x=>!x.isActive).length},{label:"Experience",href:"/admin/experience",published:experience.length,pending:0}];const unread=messages.filter(x=>x.status==="new").length;return <div className={styles.dashboard}><AdminPageHeader eyebrow="Overview" title="Dashboard" description="A simple operational view of website content and enquiries."/><section className={styles.overviewGrid} aria-label="Content status">{cards.map(c=><Link key={c.label} href={c.href} className={styles.overviewCard}><div className={styles.overviewCopy}><span>{c.label}</span><strong>{c.published}</strong><small>Published / active · {c.pending} pending / draft</small><small>View all →</small></div></Link>)}</section><section className={styles.panel}><div className={styles.sectionHeading}><div><p>Inbox</p><h2>Enquiries</h2></div><Link href="/admin/messages" className={styles.sectionLink}>View all</Link></div><div className={styles.messageStatusGrid}><div className={`${styles.messageStatusCard} ${styles.messageNew}`}><strong>{messages.length}</strong><span>Total</span></div><div className={`${styles.messageStatusCard} ${styles.messageRead}`}><strong>{unread}</strong><span>New / unread</span></div></div><div className={styles.enquiryList}>{recent.map(m=><Link href="/admin/messages" key={m.id} className={`${styles.enquiryRow} ${m.status==="new"?styles.enquiryNew:""}`}><div className={styles.enquiryTop}><div className={styles.enquiryIdentity}><strong>{m.name}</strong><span>{m.status}</span></div></div><p>{m.message}</p></Link>)}{recent.length===0&&<div className={styles.emptyState}><p>No enquiries yet.</p></div>}</div></section></div>}
