export const PAGE_CONTENT_KEYS = ["global", "about", "services", "experience", "portfolio", "contact"] as const;
export type PageContentKey = (typeof PAGE_CONTENT_KEYS)[number];

export type PageContentField = Readonly<{
  key: string;
  label: string;
  kind?: "input" | "textarea" | "url" | "image" | "contact-options";
  maxLength?: number;
  defaultValue: string;
}>;

export const PAGE_CONTENT_CONFIG: Record<PageContentKey, { label: string; fields: readonly PageContentField[] }> = {
  global: {
    label: "Header & Footer",
    fields: [
      { key: "headerRoleLabel", label: "Header Role Label", defaultValue: "Video Editor" },
      { key: "navHomeLabel", label: "Navigation — Home", defaultValue: "Home" },
      { key: "navAboutLabel", label: "Navigation — About", defaultValue: "About" },
      { key: "navPortfolioLabel", label: "Navigation — Portfolio", defaultValue: "Portfolio" },
      { key: "navServicesLabel", label: "Navigation — Services", defaultValue: "Services" },
      { key: "navExperienceLabel", label: "Navigation — Experience", defaultValue: "Experience" },
      { key: "navContactLabel", label: "Navigation — Contact", defaultValue: "Contact" },
      { key: "headerCtaLabel", label: "Header CTA Label", defaultValue: "Let’s Talk" },
      { key: "headerCtaUrl", label: "Header CTA URL", kind: "url", defaultValue: "/contact" },
      { key: "footerEyebrow", label: "Footer Eyebrow", defaultValue: "Have a project in mind?" },
      { key: "footerHeadingLine1", label: "Footer Heading Line 1", defaultValue: "Let’s create" },
      { key: "footerHeadingLine2", label: "Footer Heading Line 2", defaultValue: "something" },
      { key: "footerHeadingAccent", label: "Footer Accent Line", defaultValue: "worth watching." },
      { key: "footerCtaDescription", label: "Footer CTA Description", kind: "textarea", maxLength: 500, defaultValue: "Share the project and what you want the final edit to communicate." },
      { key: "footerCtaLabel", label: "Footer CTA Label", defaultValue: "Start a project" },
      { key: "footerCtaUrl", label: "Footer CTA URL", kind: "url", defaultValue: "/contact" },
      { key: "footerRoleLabel", label: "Footer Role Label", defaultValue: "Video Editor & Visual Storyteller" },
      { key: "footerExploreLabel", label: "Explore Column Label", defaultValue: "Explore" },
      { key: "footerExpertiseLabel", label: "Expertise Column Label", defaultValue: "Expertise" },
      { key: "footerEmailLabel", label: "Footer Contact Label — Email", defaultValue: "Email" },
      { key: "footerPhoneLabel", label: "Footer Contact Label — Phone", defaultValue: "Phone" },
      { key: "footerLocationLabel", label: "Footer Contact Label — Location", defaultValue: "Location" },
      { key: "footerAvailabilityLabel", label: "Footer Contact Label — Availability", defaultValue: "Availability" },
      { key: "footerSocialEyebrow", label: "Social Eyebrow", defaultValue: "Social presence" },
      { key: "footerSocialHeading", label: "Social Heading", defaultValue: "Follow my work" },
      { key: "footerCopyrightRole", label: "Copyright Role Label", defaultValue: "Video Editor" },
      { key: "footerAdminLabel", label: "Footer Admin Link Label", defaultValue: "Admin" },
    ],
  },
  about: {
    label: "About Page",
    fields: [
      { key: "heroEyebrow", label: "Hero Eyebrow", defaultValue: "About the editor" },
      { key: "heroPrimaryLabel", label: "Hero Primary Button", defaultValue: "View portfolio" },
      { key: "heroPrimaryUrl", label: "Hero Primary URL", kind: "url", defaultValue: "/portfolio" },
      { key: "heroSecondaryLabel", label: "Hero Secondary Button", defaultValue: "Start a conversation" },
      { key: "heroSecondaryUrl", label: "Hero Secondary URL", kind: "url", defaultValue: "/contact" },
      { key: "storyEyebrow", label: "Story Eyebrow", defaultValue: "My story" },
      { key: "storyHeading", label: "Story Heading", kind: "textarea", maxLength: 240, defaultValue: "Craft first. Technology in service of the story." },
      { key: "skillsLabel", label: "Skills Label", defaultValue: "Skills" },
      { key: "toolsLabel", label: "Tools Label", defaultValue: "Tools I use" },
      { key: "ctaEyebrow", label: "Bottom CTA Eyebrow", defaultValue: "Next chapter" },
      { key: "ctaHeading", label: "Bottom CTA Heading", kind: "textarea", maxLength: 240, defaultValue: "Bring the next story into focus." },
      { key: "ctaDescription", label: "Bottom CTA Description", kind: "textarea", maxLength: 500, defaultValue: "Explore the work or start a conversation about your project." },
      { key: "ctaPrimaryLabel", label: "Bottom Primary Button", defaultValue: "Start a conversation" },
      { key: "ctaPrimaryUrl", label: "Bottom Primary URL", kind: "url", defaultValue: "/contact" },
      { key: "ctaSecondaryLabel", label: "Bottom Secondary Button", defaultValue: "View portfolio" },
      { key: "ctaSecondaryUrl", label: "Bottom Secondary URL", kind: "url", defaultValue: "/portfolio" },
    ],
  },
  services: {
    label: "Services Page",
    fields: [
      { key: "heroEyebrow", label: "Hero Eyebrow", defaultValue: "Services" },
      { key: "heroHeading", label: "Hero Heading", kind: "textarea", maxLength: 240, defaultValue: "How I can help tell your story" },
      { key: "heroDescription", label: "Hero Description", kind: "textarea", maxLength: 600, defaultValue: "From YouTube documentaries to fast-paced social reels, I offer end-to-end post-production so you can focus on creating — I’ll handle the edit." },
      { key: "heroImageUrl", label: "Services Hero Image", kind: "image", defaultValue: "" },
      { key: "heroImageAlt", label: "Services Hero Image Alt Text", maxLength: 240, defaultValue: "Video editor working at a desktop editing setup" },
      { key: "activeServiceSingular", label: "Active Service Count — Singular", defaultValue: "Active service" },
      { key: "activeServicePlural", label: "Active Service Count — Plural", defaultValue: "Active services" },
      { key: "showcaseEyebrow", label: "Services Showcase Eyebrow", defaultValue: "What I offer" },
      { key: "showcaseHeading", label: "Services Showcase Heading", defaultValue: "Services built around the story." },
      { key: "showcaseDescription", label: "Services Showcase Description", kind: "textarea", maxLength: 500, defaultValue: "Every active service below is drawn directly from the current service catalog." },
      { key: "showcaseEmptyText", label: "Services Empty State", defaultValue: "No active services yet." },
      { key: "toolsEyebrow", label: "Tools Section Eyebrow", defaultValue: "Tools & technologies" },
      { key: "toolsHeading", label: "Tools Section Heading", defaultValue: "The tools behind the work." },
      { key: "processEyebrow", label: "Process Eyebrow", defaultValue: "How we work" },
      { key: "processHeading", label: "Process Heading", defaultValue: "My Process" },
      { key: "process1Title", label: "Process 1 Title", defaultValue: "Brief & Footage" },
      { key: "process1Description", label: "Process 1 Description", kind: "textarea", defaultValue: "Share your raw footage, goals and any reference edits." },
      { key: "process2Title", label: "Process 2 Title", defaultValue: "Rough Cut" },
      { key: "process2Description", label: "Process 2 Description", kind: "textarea", defaultValue: "A first pass structuring the story, pacing and key moments." },
      { key: "process3Title", label: "Process 3 Title", defaultValue: "Refine" },
      { key: "process3Description", label: "Process 3 Description", kind: "textarea", defaultValue: "Sound design, color and motion graphics layered in with your feedback." },
      { key: "process4Title", label: "Process 4 Title", defaultValue: "Deliver" },
      { key: "process4Description", label: "Process 4 Description", kind: "textarea", defaultValue: "Final export in the formats you need, ready to publish." },
    ],
  },
  experience: {
    label: "Experience Page",
    fields: [
      { key: "heroEyebrow", label: "Hero Eyebrow", defaultValue: "Experience" },
      { key: "heroHeading", label: "Hero Heading", kind: "textarea", maxLength: 240, defaultValue: "Crafting stories through experience and precision." },
      { key: "heroDescription", label: "Hero Description", kind: "textarea", maxLength: 600, defaultValue: "Over the years, I’ve worked across different industries and creative environments — sharpening my skills, understanding stories deeper, and delivering impactful edits." },
      { key: "heroImageUrl", label: "Experience Hero Image", kind: "image", defaultValue: "" },
      { key: "heroImageAlt", label: "Experience Hero Image Alt Text", maxLength: 240, defaultValue: "Video editor working at a professional editing workstation" },
      { key: "currentRoleLabel", label: "Hero Stat Label — Current Role", defaultValue: "Current role" },
      { key: "locationLabel", label: "Hero Stat Label — Location", defaultValue: "Location" },
      { key: "entriesLabel", label: "Hero Stat Label — Experience Entries", defaultValue: "Experience entries" },
      { key: "listEyebrow", label: "Experience List Eyebrow", defaultValue: "Professional journey" },
      { key: "listHeading", label: "Experience List Heading", defaultValue: "My professional experience." },
      { key: "listDescription", label: "Experience List Description", kind: "textarea", maxLength: 500, defaultValue: "A timeline of my roles and responsibilities that have shaped my journey as a video editor." },
      { key: "listEmptyText", label: "Experience Empty State", defaultValue: "Experience details will appear here when they are added." },
      { key: "presentLabel", label: "Current Experience End-date Label", defaultValue: "Present" },
      { key: "currentBadgeLabel", label: "Current Experience Badge", defaultValue: "Current" },
      { key: "capabilitiesHeading", label: "Capabilities Section Heading", defaultValue: "What I work across" },
      { key: "heroPrimaryLabel", label: "Hero Primary Button", defaultValue: "View My Work" },
      { key: "heroPrimaryUrl", label: "Hero Primary URL", kind: "url", defaultValue: "/portfolio" },
      { key: "heroSecondaryLabel", label: "Hero Secondary Button", defaultValue: "Let’s Connect" },
      { key: "heroSecondaryUrl", label: "Hero Secondary URL", kind: "url", defaultValue: "/contact" },
      { key: "ctaEyebrow", label: "Bottom CTA Eyebrow", defaultValue: "Next chapter" },
      { key: "ctaHeading", label: "Bottom CTA Heading", defaultValue: "Have a project in mind?" },
      { key: "ctaDescription", label: "Bottom CTA Description", kind: "textarea", defaultValue: "Let’s collaborate and create something impactful together." },
      { key: "ctaPrimaryLabel", label: "Bottom Primary Button", defaultValue: "Start a Conversation" },
      { key: "ctaPrimaryUrl", label: "Bottom Primary URL", kind: "url", defaultValue: "/contact" },
      { key: "ctaSecondaryLabel", label: "Bottom Secondary Button", defaultValue: "View Portfolio" },
      { key: "ctaSecondaryUrl", label: "Bottom Secondary URL", kind: "url", defaultValue: "/portfolio" },
    ],
  },
  portfolio: {
    label: "Portfolio Page",
    fields: [
      { key: "heroEyebrow", label: "Hero Eyebrow", defaultValue: "Selected work" },
      { key: "heroHeading", label: "Hero Heading", kind: "textarea", maxLength: 240, defaultValue: "Stories shaped to hold attention." },
      { key: "heroDescription", label: "Hero Description", kind: "textarea", maxLength: 600, defaultValue: "Editing work across formats, built around clarity, pacing, and the moments that make a story land." },
      { key: "filterAllLabel", label: "Category Filter — All", defaultValue: "All" },
      { key: "filterAriaLabel", label: "Category Filter Accessibility Label", defaultValue: "Filter projects by category" },
      { key: "collectionEyebrow", label: "Collection Eyebrow", defaultValue: "Project collection" },
      { key: "collectionHeading", label: "Collection Heading", defaultValue: "More selected work." },
      { key: "collectionProjectSingular", label: "Collection Count — Singular", defaultValue: "project" },
      { key: "collectionProjectPlural", label: "Collection Count — Plural", defaultValue: "projects" },
      { key: "caseStudyEyebrow", label: "Case Study Eyebrow", defaultValue: "Featured case study" },
      { key: "caseStudyLinkLabel", label: "Case Study Link Label", defaultValue: "View case study" },
      { key: "emptyHeading", label: "Empty State Heading", defaultValue: "No projects here yet." },
      { key: "emptyDescription", label: "Empty State Description", kind: "textarea", defaultValue: "Published work will appear here when it is available." },
      { key: "filteredEmptyDescription", label: "Filtered Empty State Description", kind: "textarea", defaultValue: "No published work matches this category at the moment." },
      { key: "cardFeaturedLabel", label: "Project Card Featured Label", defaultValue: "Featured project" },
      { key: "cardViewLabel", label: "Project Card View Label", defaultValue: "View project" },
      { key: "cardFallbackCategoryLabel", label: "Project Card Fallback Category", defaultValue: "Selected project" },
      { key: "cardPreviewAltSuffix", label: "Project Card Preview Alt Suffix", defaultValue: "project preview" },
      { key: "detailSelectedProjectLabel", label: "Project Detail Fallback Category Label", defaultValue: "Selected project" },
      { key: "detailOverviewEyebrow", label: "Project Detail Overview Eyebrow", defaultValue: "Project overview" },
      { key: "detailClientLabel", label: "Project Detail Client Label", defaultValue: "Client" },
      { key: "detailCategoryLabel", label: "Project Detail Category Label", defaultValue: "Category" },
      { key: "detailYearLabel", label: "Project Detail Year Label", defaultValue: "Year" },
      { key: "detailCaseStudyEyebrow", label: "Project Detail Case Study Eyebrow", defaultValue: "Case study" },
      { key: "detailChallengeLabel", label: "Project Detail Challenge Label", defaultValue: "Challenge" },
      { key: "detailApproachLabel", label: "Project Detail Approach Label", defaultValue: "Approach" },
      { key: "detailResultLabel", label: "Project Detail Result Label", defaultValue: "Result" },
      { key: "detailToolsEyebrow", label: "Project Detail Tools Eyebrow", defaultValue: "Tools" },
      { key: "detailToolsHeading", label: "Project Detail Tools Heading", defaultValue: "Project toolkit." },
      { key: "detailToolsAriaLabel", label: "Project Detail Tools Accessibility Label", defaultValue: "Tools used" },
      { key: "detailMediaEyebrow", label: "Project Detail Additional Media Eyebrow", defaultValue: "Additional media" },
      { key: "detailMediaHeading", label: "Project Detail Additional Media Heading", defaultValue: "More from the project." },
      { key: "detailPreviewAltSuffix", label: "Project Preview Alt Text Suffix", defaultValue: "project preview" },
      { key: "detailMediaAltSuffix", label: "Project Media Alt Text Suffix", defaultValue: "project media" },
      { key: "ctaEyebrow", label: "Bottom CTA Eyebrow", defaultValue: "Next project" },
      { key: "ctaHeading", label: "Bottom CTA Heading", defaultValue: "Bring the next story into focus." },
      { key: "ctaDescription", label: "Bottom CTA Description", kind: "textarea", defaultValue: "Share the brief, the footage, or simply the idea. We can shape the next piece together." },
      { key: "ctaLabel", label: "Bottom CTA Button", defaultValue: "Start a Conversation" },
      { key: "ctaUrl", label: "Bottom CTA URL", kind: "url", defaultValue: "/contact" },
    ],
  },
  contact: {
    label: "Contact Page",
    fields: [
      { key: "heroEyebrow", label: "Hero Eyebrow", defaultValue: "Contact" },
      { key: "heroTitleBefore", label: "Hero Title Before Accent", defaultValue: "Let’s create something" },
      { key: "heroTitleAccent", label: "Hero Accent Word", defaultValue: "impactful" },
      { key: "heroTitleAfter", label: "Hero Title After Accent", defaultValue: "together." },
      { key: "heroDescription", label: "Hero Description", kind: "textarea", maxLength: 600, defaultValue: "Have a project in mind or want to discuss an idea? I’d love to hear from you. Let’s bring your story to life." },
      { key: "heroImageUrl", label: "Contact Hero Image", kind: "image", defaultValue: "" },
      { key: "heroImageAlt", label: "Contact Hero Image Alt Text", maxLength: 240, defaultValue: "Video editor working at a professional editing workstation" },
      { key: "infoEyebrow", label: "Contact Details Eyebrow", defaultValue: "Let’s connect" },
      { key: "infoHeadingBefore", label: "Contact Details Heading Before Accent", defaultValue: "Great ideas deserve the right" },
      { key: "infoHeadingAccent", label: "Contact Details Heading Accent", defaultValue: "collaboration." },
      { key: "infoDescription", label: "Contact Details Description", kind: "textarea", maxLength: 500, defaultValue: "Share your goals, vision, and requirements. I’ll use them to understand the right approach for your project." },
      { key: "infoOfficialLabel", label: "Official Details Section Label", defaultValue: "Official details" },
      { key: "infoNameLabel", label: "Official Detail — Name", defaultValue: "Name" },
      { key: "infoEmailLabel", label: "Official Detail — Email", defaultValue: "Email" },
      { key: "infoPhoneLabel", label: "Official Detail — Phone", defaultValue: "Phone" },
      { key: "infoWhatsappLabel", label: "Official Detail — WhatsApp", defaultValue: "WhatsApp" },
      { key: "infoLocationLabel", label: "Official Detail — Location", defaultValue: "Location" },
      { key: "infoAvailabilityLabel", label: "Official Detail — Availability", defaultValue: "Availability" },
      { key: "infoFollowLabel", label: "Social Links Label", defaultValue: "Follow me" },
      { key: "infoWorkingTermsLabel", label: "Working Terms Section Label", defaultValue: "Working terms" },
      { key: "infoPaymentTermsLabel", label: "Working Term — Payment Terms", defaultValue: "Payment terms" },
      { key: "infoTurnaroundLabel", label: "Working Term — Turnaround Time", defaultValue: "Turnaround time" },
      { key: "formHeading", label: "Contact Form Heading", defaultValue: "Send a Message" },
      { key: "formDescription", label: "Contact Form Description", kind: "textarea", maxLength: 500, defaultValue: "Share the brief, timeline, and references so I can understand what your project needs." },
      { key: "formAriaLabel", label: "Contact Form Accessibility Label", defaultValue: "Project inquiry form" },
      { key: "formRequiredLabel", label: "Required Fields Note", defaultValue: "Required fields" },
      { key: "formNameLabel", label: "Name Field Label", defaultValue: "Your Name" },
      { key: "formNamePlaceholder", label: "Name Placeholder", defaultValue: "Your name" },
      { key: "formEmailLabel", label: "Email Field Label", defaultValue: "Email Address" },
      { key: "formEmailPlaceholder", label: "Email Placeholder", defaultValue: "you@example.com" },
      { key: "formPhoneLabel", label: "Phone Field Label", defaultValue: "Phone Number" },
      { key: "formPhonePlaceholder", label: "Phone Placeholder", defaultValue: "Optional" },
      { key: "formBudgetLabel", label: "Budget Field Label", defaultValue: "Budget Range" },
      { key: "formBudgetPlaceholder", label: "Budget Placeholder", defaultValue: "Select budget" },
      { key: "formCategoryLabel", label: "Category Field Label", defaultValue: "Project Category" },
      { key: "formCategoryPlaceholder", label: "Category Placeholder", defaultValue: "Select category" },
      { key: "formOtherCategoryLabel", label: "Category Option — Other", defaultValue: "Other" },
      { key: "formVideoTypeLabel", label: "Video Type Field Label", defaultValue: "Video Type" },
      { key: "formVideoTypePlaceholder", label: "Video Type Placeholder", defaultValue: "Select video type" },
      { key: "formTimelineLabel", label: "Timeline Field Label", defaultValue: "Project Timeline" },
      { key: "formTimelinePlaceholder", label: "Timeline Placeholder", defaultValue: "Select desired timeline" },
      { key: "formReferenceLabel", label: "Reference Field Label", defaultValue: "Reference Link" },
      { key: "formOptionalLabel", label: "Optional Label", defaultValue: "Optional" },
      { key: "formReferencePlaceholder", label: "Reference Placeholder", defaultValue: "https://" },
      { key: "formMessageLabel", label: "Message Field Label", defaultValue: "Tell me more about your project" },
      { key: "formMessagePlaceholder", label: "Message Placeholder", kind: "textarea", maxLength: 500, defaultValue: "Share the goals, audience, style, and any specific requirements." },
      { key: "formMessageHelper", label: "Message Helper Text", kind: "textarea", maxLength: 500, defaultValue: "Include the project goals, target audience, preferred style, and key requirements." },
      { key: "formSubmitLabel", label: "Submit Button Label", defaultValue: "Send Message" },
      { key: "formSendingLabel", label: "Sending Button Label", defaultValue: "Sending message…" },
      { key: "formSuccessHeading", label: "Success Heading", defaultValue: "Message sent!" },
      { key: "portfolioCtaHeading", label: "Portfolio CTA Heading", defaultValue: "Have a project to discuss?" },
      { key: "portfolioCtaDescription", label: "Portfolio CTA Description", kind: "textarea", defaultValue: "Explore the work and see how different stories have been shaped." },
      { key: "portfolioCtaLabel", label: "Portfolio CTA Button", defaultValue: "View My Work" },
      { key: "portfolioCtaUrl", label: "Portfolio CTA URL", kind: "url", defaultValue: "/portfolio" },
      { key: "popupEyebrow", label: "Popup Eyebrow", defaultValue: "Get in touch" },
      { key: "popupTitle", label: "Popup Main Title", defaultValue: "Let’s talk" },
      { key: "popupTitleAccent", label: "Popup Accent Title", defaultValue: "About Your Project" },
      { key: "popupDescription", label: "Popup Description", kind: "textarea", maxLength: 500, defaultValue: "Have a project in mind? I’d love to hear from you. Let’s create something amazing together." },
      { key: "popupCloseLabel", label: "Popup Close Accessibility Label", defaultValue: "Close contact form" },
      { key: "popupFormAriaLabel", label: "Popup Form Accessibility Label", defaultValue: "Project inquiry form" },
      { key: "popupNameLabel", label: "Popup Name Label", defaultValue: "Your Name" },
      { key: "popupNamePlaceholder", label: "Popup Name Placeholder", defaultValue: "Your Name" },
      { key: "popupEmailLabel", label: "Popup Email Label", defaultValue: "Your Email" },
      { key: "popupEmailPlaceholder", label: "Popup Email Placeholder", defaultValue: "Your Email" },
      { key: "popupPhoneLabel", label: "Popup Phone Label", defaultValue: "Phone Number" },
      { key: "popupPhonePlaceholder", label: "Popup Phone Placeholder", defaultValue: "Phone Number" },
      { key: "popupProjectTypeLabel", label: "Popup Project Type Label", defaultValue: "Project Type" },
      { key: "popupProjectTypePlaceholder", label: "Popup Project Type Placeholder", defaultValue: "Project Type" },
      { key: "popupBudgetLabel", label: "Popup Budget Label", defaultValue: "Your Budget (Optional)" },
      { key: "popupBudgetPlaceholder", label: "Popup Budget Placeholder", defaultValue: "Your Budget (Optional)" },
      { key: "popupMessageLabel", label: "Popup Message Label", defaultValue: "Your Message" },
      { key: "popupMessagePlaceholder", label: "Popup Message Placeholder", defaultValue: "Your Message" },
      { key: "popupSubmitLabel", label: "Popup Submit Label", defaultValue: "Let’s Talk" },
      { key: "popupSendingLabel", label: "Popup Sending Label", defaultValue: "Sending..." },
      { key: "popupSuccessHeading", label: "Popup Success Heading", defaultValue: "Message sent" },
      { key: "popupBenefitQuick", label: "Popup Benefit — Quick Response", defaultValue: "Quick response" },
      { key: "popupBenefitPrivacy", label: "Popup Benefit — Privacy", defaultValue: "Project details kept private" },
      { key: "popupBenefitProfessional", label: "Popup Benefit — Communication", defaultValue: "Professional communication" },
    ],
  },
};

export function defaultPageContent(pageKey: PageContentKey): Record<string, string> {
  return Object.fromEntries(PAGE_CONTENT_CONFIG[pageKey].fields.map((field) => [field.key, field.defaultValue]));
}
