import type { Metadata } from "next";
import type { PageSeoRecord } from "@/lib/db/page-seo-service";
export const SITE_NAME="Lucky Saroj";export const DEFAULT_SITE_TITLE="Lucky Saroj — Video Editor & Visual Storyteller";export const DEFAULT_SITE_DESCRIPTION="Portfolio of Lucky Saroj, a freelance video editor specializing in YouTube documentaries, commercials, reels and motion graphics.";export const FALLBACK_SITE_ORIGIN="https://lucky-saroj-portfolio.vercel.app";
type SeoEnvironment=Record<string,string|undefined>&{NEXT_PUBLIC_SITE_URL?:string;VERCEL_PROJECT_PRODUCTION_URL?:string};
function parseOrigin(value:string):URL|null{try{const p=new URL(value);if(!new Set(["http:","https:"]).has(p.protocol)||p.username||p.password||p.search||p.hash)return null;p.pathname="/";return p}catch{return null}}
export function resolveSiteUrl(environment:SeoEnvironment=process.env):URL{const c=environment.NEXT_PUBLIC_SITE_URL?.trim();if(c){const p=parseOrigin(c);if(p)return p}const h=environment.VERCEL_PROJECT_PRODUCTION_URL?.trim();if(h){const p=parseOrigin(`https://${h.replace(/^https?:\/\//,"")}`);if(p)return p}return new URL(FALLBACK_SITE_ORIGIN)}
export function absoluteSiteUrl(pathname:string,environment?:SeoEnvironment):string{return new URL(pathname,resolveSiteUrl(environment)).toString()}
function normalizeSocialImage(image:string|null|undefined):string[]|undefined{const v=image?.trim();if(!v)return undefined;try{return[new URL(v,resolveSiteUrl()).toString()]}catch{return undefined}}
export function createPageMetadata(input:{title:string;description:string;path:string;image?:string|null;keywords?:string[];robotsIndex?:boolean}):Metadata{const images=normalizeSocialImage(input.image),index=input.robotsIndex??true;return{title:input.title,description:input.description,...(input.keywords?.length?{keywords:input.keywords}:{}),alternates:{canonical:input.path},robots:index?{index:true,follow:true}:{index:false,follow:false,nocache:true},openGraph:{type:"website",siteName:SITE_NAME,title:input.title,description:input.description,url:input.path,...(images?{images}:{})},twitter:{card:images?"summary_large_image":"summary",title:input.title,description:input.description,...(images?{images}:{})}}}
export function createCmsPageMetadata(seo:PageSeoRecord,globalImage?:string|null):Metadata{const ogTitle=seo.ogTitle||seo.metaTitle,ogDescription=seo.ogDescription||seo.metaDescription,ogImage=seo.ogImageUrl||globalImage||null,twitterTitle=seo.twitterTitle||ogTitle,twitterDescription=seo.twitterDescription||ogDescription,twitterImage=seo.twitterImageUrl||ogImage;const ogImages=normalizeSocialImage(ogImage),twitterImages=normalizeSocialImage(twitterImage),keywords=seo.keywords.split(",").map(x=>x.trim()).filter(Boolean);return{title:seo.metaTitle,description:seo.metaDescription,...(keywords.length?{keywords}:{}),alternates:{canonical:seo.canonicalPath},robots:seo.robotsIndex?{index:true,follow:true}:{index:false,follow:false,nocache:true},openGraph:{type:"website",siteName:SITE_NAME,title:ogTitle,description:ogDescription,url:seo.canonicalPath,...(ogImages?{images:ogImages}:{})},twitter:{card:twitterImages?"summary_large_image":"summary",title:twitterTitle,description:twitterDescription,...(twitterImages?{images:twitterImages}:{})}}}
