"use client";
import { useActionState } from "react";
import { Label, Input, Textarea } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { FieldError, FormCard } from "@/components/admin/FormParts";
import { updateSettings } from "@/lib/actions/settings";
import type { ActionState } from "@/lib/actions/portfolio";
import type { schema } from "@/lib/db";
import { MediaForm } from "@/components/admin/MediaForm";
import { FileUpload } from "@/components/admin/FileUpload";
import styles from "./AdminEditorial.module.css";
type BaseSettings=typeof schema.siteSettings.$inferSelect;type Settings=BaseSettings&{twitterCardType:"summary"|"summary_large_image";twitterSiteUsername:string|null;robotsTxt:string};
const initialState:ActionState={status:"idle"};type AssetBindings={logoImageAssetId?:string|null;heroImageAssetId?:string|null;faviconAssetId?:string|null;ogImageAssetId?:string|null};
export function SeoGlobalSettingsForm({settings,assets}:{settings:Settings;assets:AssetBindings}){const[state,formAction,pending]=useActionState(updateSettings,initialState);return <MediaForm action={formAction} className={styles.sectionStack}>
<input type="hidden" name="revision" value={settings.revision}/><input type="hidden" name="logoText" value={settings.logoText??"LS"}/><input type="hidden" name="logoImageUrl" value={settings.logoImageUrl??""}/><input type="hidden" name="logoImageAssetId" value={assets.logoImageAssetId??""}/><input type="hidden" name="contactEmail" value={settings.contactEmail??""}/><input type="hidden" name="contactPhone" value={settings.contactPhone??""}/><input type="hidden" name="whatsapp" value={settings.whatsapp??""}/><input type="hidden" name="location" value={settings.location??""}/><input type="hidden" name="availability" value={settings.availability??""}/><input type="hidden" name="paymentTerms" value={settings.paymentTerms??""}/><input type="hidden" name="turnaroundTime" value={settings.turnaroundTime??""}/><input type="hidden" name="heroHeading" value={settings.heroHeading??""}/><input type="hidden" name="heroSubheading" value={settings.heroSubheading??""}/><input type="hidden" name="heroDescription" value={settings.heroDescription??""}/><input type="hidden" name="heroImageUrl" value={settings.heroImageUrl??""}/><input type="hidden" name="heroImageAssetId" value={assets.heroImageAssetId??""}/><input type="hidden" name="statYears" value={settings.statYears??""}/><input type="hidden" name="statProjects" value={settings.statProjects??""}/><input type="hidden" name="statClients" value={settings.statClients??""}/><input type="hidden" name="statViews" value={settings.statViews??""}/><input type="hidden" name="footerDescription" value={settings.footerDescription??""}/><input type="hidden" name="instagramUrl" value={settings.instagramUrl??""}/><input type="hidden" name="twitterUrl" value={settings.twitterUrl??""}/><input type="hidden" name="youtubeUrl" value={settings.youtubeUrl??""}/><input type="hidden" name="linkedinUrl" value={settings.linkedinUrl??""}/><input type="hidden" name="behanceUrl" value={settings.behanceUrl??""}/><input type="hidden" name="vimeoUrl" value={settings.vimeoUrl??""}/>
<FormCard title="Global & Technical SEO"><div><Label htmlFor="siteName">Site Name</Label><Input id="siteName" name="siteName" defaultValue={settings.siteName??"Lucky Saroj"} required/></div><div><Label htmlFor="seoTitle">Default Meta Title</Label><Input id="seoTitle" name="seoTitle" defaultValue={settings.seoTitle??""} required/></div><div><Label htmlFor="seoDescription">Default Meta Description</Label><Textarea id="seoDescription" name="seoDescription" rows={3} defaultValue={settings.seoDescription??""}/></div><FileUpload name="favicon" assetIdName="faviconAssetId" label="Favicon" kind="image" defaultValue={settings.favicon} defaultAssetId={assets.faviconAssetId}/><FileUpload name="ogImageUrl" assetIdName="ogImageAssetId" label="Default Open Graph / Twitter Image" kind="image" defaultValue={settings.ogImageUrl} defaultAssetId={assets.ogImageAssetId}/><div><Label htmlFor="twitterCardType">Default Twitter Card</Label><select id="twitterCardType" name="twitterCardType" defaultValue={settings.twitterCardType}><option value="summary_large_image">Large image</option><option value="summary">Summary</option></select></div><div><Label htmlFor="twitterSiteUsername">Twitter / X Site Username</Label><Input id="twitterSiteUsername" name="twitterSiteUsername" placeholder="@username" defaultValue={settings.twitterSiteUsername??""}/><FieldError message={state.fieldErrors?.twitterSiteUsername}/></div><div><Label htmlFor="googleSiteVerification">Google Search Console Verification Code</Label><Input id="googleSiteVerification" name="googleSiteVerification" maxLength={512} defaultValue={settings.googleSiteVerification??""}/><FieldError message={state.fieldErrors?.googleSiteVerification}/></div><div><Label htmlFor="googleAnalyticsMeasurementId">Google Analytics Measurement ID</Label><Input id="googleAnalyticsMeasurementId" name="googleAnalyticsMeasurementId" placeholder="G-XXXXXXXXXX" defaultValue={settings.googleAnalyticsMeasurementId??""}/></div><div><Label htmlFor="robotsTxt">robots.txt</Label><Textarea id="robotsTxt" name="robotsTxt" rows={10} defaultValue={settings.robotsTxt}/><p className={styles.helper}>Admin and API routes remain blocked by the public robots route even if omitted here. Use HTTPS for Sitemap/Host directives.</p><FieldError message={state.fieldErrors?.robotsTxt}/></div></FormCard>
{state.status==="error"&&state.message&&<p className={styles.feedbackError}>{state.message}</p>}{state.status==="success"&&state.message&&<p className={styles.feedbackSuccess}>{state.message}</p>}<div className={styles.saveBar}><Button type="submit" disabled={pending}>{pending?"Saving...":"Save Global SEO"}</Button></div></MediaForm>}
