"use client";

import { useActionState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Input, Textarea } from "@/components/ui/Input";
import { submitFullContactForm, type ContactFormState } from "@/lib/actions/contact";
import { CONTACT_COUNTRY_CODES } from "@/lib/contact/country-codes";
import { ContactAttachmentField } from "./ContactAttachmentField";

const initialState: ContactFormState = { status: "idle" };
const fieldClasses = "min-h-[3.25rem] !rounded-md !border-white/10 !bg-[var(--surface-primary)] px-4 !text-[var(--text-primary)] placeholder:!text-[var(--text-readable, var(--text-muted))] transition-[border-color,box-shadow,background-color] duration-200 focus:!border-[var(--accent-primary)] focus:!bg-[var(--surface-primary)] focus:ring-2 focus:ring-[var(--accent-hover)] focus:ring-offset-2 focus:ring-offset-[var(--background-primary)] disabled:cursor-not-allowed disabled:opacity-60 motion-reduce:transition-none";
const labelClasses = "mb-2 block text-sm font-medium text-[var(--text-primary)]";
const errorClasses = "mt-1.5 text-xs leading-5 text-red-300";
function RequiredMark() { return <span className="text-[var(--accent-primary)]" aria-hidden>*</span>; }

export function ContactForm({ content = {} }: { projectCategories?: string[]; content?: Record<string, string> }) {
  const [state, formAction, pending] = useActionState(submitFullContactForm, initialState);
  const copy = { ariaLabel: content.formAriaLabel || "Project inquiry form", required: content.formRequiredLabel || "Required fields", nameLabel: content.formNameLabel || "Your Name", namePlaceholder: content.formNamePlaceholder || "Your name", emailLabel: content.formEmailLabel || "Email Address", emailPlaceholder: content.formEmailPlaceholder || "you@example.com", phoneLabel: content.formPhoneLabel || "Phone Number", phonePlaceholder: content.formPhonePlaceholder || "Optional", messageLabel: content.formMessageLabel || "Tell me about your project", messagePlaceholder: content.formMessagePlaceholder || "Share the goal, audience, style, timeline, budget or references here if they are useful.", messageHelper: content.formMessageHelper || "A short brief is enough — I’ll ask for anything else needed.", submitLabel: content.formSubmitLabel || "Send Message", sendingLabel: content.formSendingLabel || "Sending message…", successHeading: content.formSuccessHeading || "Message sent!" };
  if (state.status === "success") return <div className="flex min-h-72 flex-col items-center justify-center gap-3 rounded-md border border-[var(--accent-primary)]/35 bg-[var(--surface-elevated)] p-8 text-center" role="status" aria-live="polite"><CheckCircle2 className="text-[var(--accent-primary)]" size={36} aria-hidden /><p className="font-display text-2xl font-semibold text-[var(--text-primary)]">{copy.successHeading}</p><p className="max-w-md text-sm leading-6 text-[var(--text-secondary)]">{state.message}</p></div>;
  return <form action={formAction} className="space-y-5" aria-label={copy.ariaLabel} aria-busy={pending}>
    <input type="hidden" name="projectType" value="" /><input type="hidden" name="budgetRange" value="" /><input type="hidden" name="videoType" value="" /><input type="hidden" name="projectTimeline" value="" />
    <div hidden aria-hidden="true"><label htmlFor="contact-website">Website</label><input id="contact-website" name="website" type="text" tabIndex={-1} autoComplete="off" /></div>
    <p className="text-xs leading-5 text-[var(--text-readable, var(--text-muted))]"><span className="text-[var(--accent-primary)]" aria-hidden>*</span> {copy.required}</p>
    <div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="name" className={labelClasses}>{copy.nameLabel} <RequiredMark /></label><Input id="name" name="name" autoComplete="name" placeholder={copy.namePlaceholder} required maxLength={120} disabled={pending} className={`${fieldClasses} ${state.fieldErrors?.name ? "!border-red-400/60" : ""}`} />{state.fieldErrors?.name && <p className={errorClasses}>{state.fieldErrors.name}</p>}</div><div><label htmlFor="email" className={labelClasses}>{copy.emailLabel} <RequiredMark /></label><Input id="email" name="email" type="email" autoComplete="email" placeholder={copy.emailPlaceholder} required disabled={pending} className={`${fieldClasses} ${state.fieldErrors?.email ? "!border-red-400/60" : ""}`} />{state.fieldErrors?.email && <p className={errorClasses}>{state.fieldErrors.email}</p>}</div></div>
    <div><label htmlFor="phone" className={labelClasses}>{copy.phoneLabel}</label><div className="grid grid-cols-[minmax(8rem,0.42fr)_1fr] gap-2"><select name="countryCode" defaultValue="+91" aria-label="Country code" disabled={pending} className={fieldClasses}>{CONTACT_COUNTRY_CODES.map((item) => <option key={item.code} value={item.code} className="bg-[var(--surface-primary)]">{item.label}</option>)}</select><Input id="phone" name="phone" type="tel" autoComplete="tel-national" placeholder={copy.phonePlaceholder} maxLength={20} disabled={pending} className={`${fieldClasses} ${state.fieldErrors?.phone ? "!border-red-400/60" : ""}`} /></div>{state.fieldErrors?.phone && <p className={errorClasses}>{state.fieldErrors.phone}</p>}</div>
    <div><label htmlFor="message" className={labelClasses}>{copy.messageLabel} <RequiredMark /></label><Textarea id="message" name="message" rows={7} placeholder={copy.messagePlaceholder} required maxLength={4000} disabled={pending} className={`${fieldClasses} min-h-44 resize-y py-4 ${state.fieldErrors?.message ? "!border-red-400/60" : ""}`} /><p className="mt-2 text-xs leading-5 text-[var(--text-readable, var(--text-muted))]">{copy.messageHelper}</p>{state.fieldErrors?.message && <p className={errorClasses}>{state.fieldErrors.message}</p>}</div>
    <ContactAttachmentField />{state.fieldErrors?.referenceUrl && <p className={errorClasses}>{state.fieldErrors.referenceUrl}</p>}
    {state.status === "error" && state.message && !state.fieldErrors && <p className="rounded-md border border-red-400/25 bg-red-400/10 px-4 py-3 text-sm text-red-200" role="alert">{state.message}</p>}
    <button type="submit" disabled={pending} className="group flex min-h-[3.25rem] w-full items-center justify-center gap-3 rounded-md bg-[var(--accent-primary)] px-6 py-3.5 text-sm font-semibold text-[var(--background-primary)] transition-[background-color,box-shadow,transform] duration-300 hover:bg-[var(--accent-hover)] hover:shadow-[0_0_28px_rgba(59,130,246,0.22)] active:scale-[0.99] disabled:pointer-events-none disabled:opacity-60 motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-hover)] focus-visible:ring-offset-4 focus-visible:ring-offset-[var(--background-primary)]">{pending ? copy.sendingLabel : copy.submitLabel}<ArrowRight size={17} className="transition-transform duration-300 group-hover:translate-x-1 motion-reduce:transition-none" aria-hidden /></button>
  </form>;
}
