"use client";

import { useActionState, useState, type ComponentType, type InputHTMLAttributes } from "react";
import { ArrowRight, CheckCircle2, Mail, Phone, ShieldCheck, SquarePen, Star, User, Wallet, Zap } from "lucide-react";
import { submitPopupContactForm, type ContactFormState } from "@/lib/actions/contact";
import { activeContactOptionLabels, parseContactOptionsConfig } from "@/lib/contact/contact-options-config";
import { CONTACT_COUNTRY_CODES } from "@/lib/contact/country-codes";
import { PopupContactSelect } from "./PopupContactSelect";
import { ContactAttachmentField } from "./ContactAttachmentField";

const initialState: ContactFormState = { status: "idle" };
const fieldClass = "min-h-[2.875rem] w-full rounded-[7px] border border-white/18 bg-[var(--surface-primary)] py-2 pl-11 pr-4 text-xs text-[var(--text-primary)] placeholder:text-[var(--text-secondary)] transition-[border-color,box-shadow,background-color] hover:border-white/30 focus:border-[var(--accent-primary)]/80 focus:bg-[var(--surface-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-primary)]/25 motion-reduce:transition-none sm:text-sm [@media(max-height:800px)]:sm:min-h-11";
const selectClass = "min-h-[2.875rem] w-full rounded-[7px] border border-white/18 bg-[var(--surface-primary)] px-2 text-xs text-[var(--text-primary)] focus:border-[var(--accent-primary)]/80 focus:outline-none focus:ring-2 focus:ring-[var(--accent-primary)]/25 sm:text-sm";
const errorClass = "mt-1.5 text-xs text-red-300";
type PopupIcon = ComponentType<{ size?: number; className?: string; "aria-hidden"?: boolean }>;
type PopupCopy = Record<string, string>;
function PopupField({ id, name, label, icon: Icon, error, ...props }: { id: string; name: string; label: string; icon: PopupIcon; error?: string } & InputHTMLAttributes<HTMLInputElement>) { return <div><label htmlFor={id} className="sr-only">{label}</label><div className="relative"><Icon size={17} className="pointer-events-none absolute left-4 top-1/2 z-10 -translate-y-1/2 text-[var(--accent-primary)]" aria-hidden={true} /><input id={id} name={name} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} className={`${fieldClass} ${error ? "border-red-400/60 hover:border-red-400/75" : ""}`} {...props} /></div>{error && <p id={`${id}-error`} className={errorClass}>{error}</p>}</div>; }

export function PopupContactForm({ copy, optionsConfig }: { copy: PopupCopy; optionsConfig?: string }) {
  const [state, formAction, pending] = useActionState(submitPopupContactForm, initialState);
  const [projectType, setProjectType] = useState(""); const [budget, setBudget] = useState("");
  const optionConfig = parseContactOptionsConfig(optionsConfig); const projectTypeOptions = activeContactOptionLabels(optionConfig, "popupProjectTypes"); const budgetOptions = activeContactOptionLabels(optionConfig, "budgetRanges");
  if (state.status === "success") return <div className="flex min-h-[390px] flex-col items-center justify-center px-6 py-14 text-center" role="status" aria-live="polite"><span className="flex h-16 w-16 items-center justify-center rounded-full border border-[var(--accent-primary)]/45 bg-[var(--accent-primary)]/10"><CheckCircle2 size={32} className="text-[var(--accent-primary)]" aria-hidden="true" /></span><h3 className="mt-6 font-display text-3xl font-semibold text-[var(--text-primary)]">{copy.popupSuccessHeading}</h3><p className="mt-3 max-w-md text-sm leading-6 text-[var(--text-secondary)]">{state.message}</p></div>;
  return <form action={formAction} className="relative -mt-px space-y-2 bg-[linear-gradient(to_bottom,var(--background-primary)_0%,var(--background-primary)_4rem)] px-5 pb-4 pt-2 sm:px-7 sm:pb-5" aria-label={copy.popupFormAriaLabel} aria-busy={pending}>
    <div hidden aria-hidden="true"><label htmlFor="popup-website">Website</label><input id="popup-website" name="website" type="text" tabIndex={-1} autoComplete="off" /></div><input type="hidden" name="videoType" value={projectType} /><input type="hidden" name="budgetRange" value={budget} />
    <PopupField id="popup-name" name="name" label={copy.popupNameLabel} icon={User} placeholder={copy.popupNameLabel} autoComplete="name" required maxLength={120} error={state.fieldErrors?.name} />
    <PopupField id="popup-email" name="email" label={copy.popupEmailLabel} icon={Mail} placeholder={copy.popupEmailLabel} type="email" autoComplete="email" required error={state.fieldErrors?.email} />
    <div className="grid grid-cols-[7.5rem_1fr] gap-2"><select name="countryCode" defaultValue="+91" aria-label="Country code" className={selectClass}>{CONTACT_COUNTRY_CODES.map((item) => <option key={item.code} value={item.code} className="bg-[var(--surface-primary)]">{item.code}</option>)}</select><PopupField id="popup-phone" name="phone" label={copy.popupPhoneLabel} icon={Phone} placeholder={copy.popupPhoneLabel} type="tel" autoComplete="tel-national" required maxLength={20} error={state.fieldErrors?.phone} /></div>
    <div><label htmlFor="popup-project-type" className="sr-only">{copy.popupProjectTypeLabel}</label><PopupContactSelect id="popup-project-type" name="projectType" placeholder={copy.popupProjectTypeLabel} options={projectTypeOptions} onValueChange={setProjectType} invalid={Boolean(state.fieldErrors?.projectType)} describedBy={state.fieldErrors?.projectType ? "popup-project-type-error" : undefined} />{state.fieldErrors?.projectType && <p id="popup-project-type-error" className={errorClass}>{state.fieldErrors.projectType}</p>}</div>
    <div><label htmlFor="popup-budget" className="sr-only">{copy.popupBudgetLabel}</label><div className="relative"><Wallet size={17} className="pointer-events-none absolute left-4 top-1/2 z-10 -translate-y-1/2 text-[var(--accent-primary)]" aria-hidden="true" /><select id="popup-budget" value={budget} onChange={(event) => setBudget(event.target.value)} className={`${fieldClass} appearance-none`}><option value="">{copy.popupBudgetLabel}</option>{budgetOptions.map((option) => <option key={option} value={option} className="bg-[var(--surface-primary)] text-[var(--text-primary)]">{option}</option>)}</select></div>{state.fieldErrors?.budgetRange && <p className={errorClass}>{state.fieldErrors.budgetRange}</p>}</div>
    <div><label htmlFor="popup-message" className="sr-only">{copy.popupMessageLabel}</label><div className="relative"><SquarePen size={17} className="pointer-events-none absolute left-4 top-3.5 z-10 text-[var(--accent-primary)]" aria-hidden="true" /><textarea id="popup-message" name="message" rows={4} placeholder={copy.popupMessageLabel} required maxLength={4000} className={`${fieldClass} min-h-[5.5rem] resize-y py-3 ${state.fieldErrors?.message ? "border-red-400/60" : ""}`} /></div>{state.fieldErrors?.message && <p className={errorClass}>{state.fieldErrors.message}</p>}</div>
    <ContactAttachmentField compact />{state.fieldErrors?.referenceUrl && <p className={errorClass}>{state.fieldErrors.referenceUrl}</p>}
    {state.status === "error" && state.message && !state.fieldErrors && <p className="rounded-md border border-red-400/25 bg-red-400/10 px-4 py-3 text-sm text-red-200" role="alert">{state.message}</p>}
    <button type="submit" disabled={pending} className="group flex min-h-12 w-full items-center justify-center gap-2.5 rounded-[7px] bg-[linear-gradient(110deg,var(--accent-primary),var(--accent-active))] px-5 py-2.5 text-xs font-semibold uppercase text-white shadow-[0_8px_26px_rgba(59,130,246,0.18)] transition-[filter,box-shadow,transform] hover:-translate-y-px hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-hover)] disabled:opacity-60 sm:text-sm">{pending ? copy.popupSendingLabel : copy.popupSubmitLabel}<ArrowRight size={17} aria-hidden="true" /></button>
    <div className="flex flex-wrap items-center justify-center gap-x-1.5 gap-y-1 pt-0.5 text-[0.625rem] text-[var(--text-secondary)]" aria-label={copy.popupBenefitsAriaLabel}><Trust icon={Zap} label={copy.popupQuickResponseLabel} /><span className="text-[var(--text-secondary)]">•</span><Trust icon={ShieldCheck} label={copy.popupPrivacyLabel} /><span className="text-[var(--text-secondary)]">•</span><Trust icon={Star} label={copy.popupCommunicationLabel} /></div>
  </form>;
}
function Trust({ icon: Icon, label }: { icon: PopupIcon; label: string }) { return <span className="inline-flex items-center gap-1 whitespace-nowrap"><Icon size={14} className="shrink-0 text-[var(--accent-primary)]" aria-hidden={true} />{label}</span>; }
